"""empty message

Revision ID: 34852ac9a0a5
Revises: 3225c810188f
Create Date: 2023-03-19 14:57:09.832251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34852ac9a0a5'
down_revision = '3225c810188f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registration', schema=None) as batch_op:
        batch_op.alter_column('course_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=10),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registration', schema=None) as batch_op:
        batch_op.alter_column('course_id',
               existing_type=sa.String(length=10),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
